MODEL:
  NAME: bank_tab
  HIDDEN_SIZE: 32
  NUM_LAYERS: 3
  NUM_HEADS: 4

TRAIN:
  RUN_NAME: v3-apply-scheduler
  BATCH_SIZE: 128
  EPOCHS: 5
  PATIENCE: 2
  
  FIRST_CYCLE_STEPS: 50
  CYCLE: 2.0
  MAX_LR: 0.001
  MIN_LR: 0.00001
  WARMUP_STEPS: 10
  GAMMA: 0.5
